
services:
  - type: web
    name: SpringBoot-Empleados
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:mysql://tu-base-de-datos:3306/empleados
      - key: DATABASE_USERNAME
        value: root
      - key: DATABASE_PASSWORD
        value: admin
      - key: SPRING_PROFILES_ACTIVE
        value: production
