services:
  - type: web
    name: empleados-springboot
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/empleados-0.0.1-SNAPSHOT.war"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    region: oregon
